language: cpp
compiler:
  - gcc
  #- clang
env:
  global:
    - ROS_DISTRO=hydro # wait until travis will update to 14.04

before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
    #- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros python-rosinstall expect
    # Setup rosdep
  - sudo rosdep init
  - rosdep update


install:
  # Create workspace
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME/src
  - cd ~/ros/ws_$REPOSITORY_NAME/src
  #- git clone https://github.com/mavlink/mavros --depth=1
  - wstool init .
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace
  - cd ../
  # Install dependencies for source repos
  - rosdep install -r -n --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
  - cd ~/ros/ws_$REPOSITORY_NAME/src/maskor_gige_cam/thirdparty/ebus_sdk/
  - chmod +x ./eBUS_SDK_4.0.6.3228_Ubuntu-12.04-x86_64.run
  - cd ~/ros/ws_$REPOSITORY_NAME/src/maskor_gige_cam/
    # install EBUS SDK
  - chmod +x ./autoinstall_eBUS_SDK.exp
  - sudo ./autoinstall_eBUS_SDK.exp
  #- sudo ln -sf /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0

before_script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - rospack profile
script:
  - cd ~/ros/ws_$REPOSITORY_NAME/
  - catkin_make
  #- catkin_make install
  # - rm -fr devel src build; source install/setup.bash

after_failure:
  - if [ -e ./build/Testing/Temporary/LastTest.log ]; then cat ./build/Testing/Temporary/LastTest.log; fi
  - find ${HOME}/.ros/test_results -type f -exec echo "== {} ==" \; -exec cat {} \;
  - for file in ${HOME}/.ros/log/rostest-*; do echo "=== $file ==="; cat $file; done

notifications:
 webhooks:
    urls:
      - https://webhooks.gitter.im/e/b6a7600f27d2bceb7b76
    on_success: change
    on_failure: always
    on_start: false
